config/routes.rb
Convocator::Application.routes.draw do
  post "memberships/create", :as => 'create_membership'
  get "memberships/approve", :as => 'approve_membership'
  get "memberships/destroy", :as => 'destroy_membership'

  get "registration" => 'registration#index', :as => 'registration' 
  get "registration/:id" => 'registration#show', :as => 'registrant'
  get "registration/:id/charges" => 'registration#charges', :as => 'registrant_charges'
  post "registration/:id/charge" => 'registration#charge', :as => 'registrant_charge'
  post "registration/charge" => 'registration#charge', :as => 'user_charge'
  post "registration/create", :as => 'create_registrant'
  get "registration/:id/qualify" => 'registration#qualifiers', :as => 'qualifiers'
  post "registration/:id/qualify" => 'registration#qualify', :as => 'qualify'
  post "registration/:id/register" => 'registration#register', :as => 'register'
  get "registration/:id/unregister" => 'registration#unregister', :as => 'unregister'
  get "registration/:id/destroy" => 'registration#destroy', :as => 'destroy_registrant'
  get "registration/:id/unwait" => 'registration#unwait', :as => 'unwait_registration'

  ActiveAdmin.routes(self)
  get "events" => 'events#index', :as => 'events'
  get "events/:id" => 'events#show', :as => 'event'
  post "events/:id" => 'events#update', :as => 'update_event'
  post "events/:id/charge" => 'events#charge', :as => 'charge_event'
  get "events/tagged/:id" => 'events#tagged', :as => 'tag'

  get "about" => 'about#index', :as => 'about'
  get "about/presenters", :as => 'presenters'
  get "about/presenters/:id" => 'about#presenter', :as => 'presenter'
  get "about/organizers", :as => 'organizers'
  get "about/organizers/:id" => 'about#organizer', :as => 'organizer'

  resources :users do
      post 'condense', :on => :member
      get 'bill', :on => :member
  end
  get "me" => 'users#me', :as => 'me'
  get 'me/edit' => 'users#edit', :as => 'edit_me'

  get "sign-in" => 'session#new', :as => 'sign_in'
  get "sign-up" => 'users#new', :as => 'sign_up'
  post "sign-in" => 'session#create', :as => 'session_create'
  get "sign-out" => 'session#destroy', :as => 'sign_out'

  get "pages" => 'pages#index', :as => 'pages'

  get '/:id' => 'pages#show', :as => 'page'

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
    has_one :presenter
    has_one :organizer
    has_many :registrants
    #has_many :charges, :through => :registrants
    #has_many :registrations, :through => :registrants
    #has_many :events, :through => :registrations
    has_secure_password
    validates :email, uniqueness: true

    attr_accessor :name

    def charges
      Charge.where(:registrant_id => self.registrant_ids).order('created_at DESC')
    end

    def balance
        self.registrants.count > 0 ? self.registrants.map{|c| c.balance || 0}.inject(0, :+) : 0
    end

    def condense_charges target
        b = BigDecimal.new '0'
        registrants.each do |r|
            unless r == target
                b += r.balance
                Charge.create(:charger => nil, :amount => -r.balance, :comment => "Condensing Charges on #{target.name}", :description => nil, :icon => 'exchange', :registrant_id => r.id)
            end
        end
        Charge.create(:charger => nil, :amount => b, :comment => 'Condensed Charges', :description => nil, :icon => 'exchange', :registrant_id => target.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :check_for_user, :except => [:new, :create]
    before_action :check_for_organizer, :only => [:index]

    def index
        @users = User.all
    end

    # GET /users/new
    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
        redirect_to me_path, :notice => "You can't do that." unless current_user == @user || current_organizer
    end

    def me
        @user = current_user
        render :show
    end

    def edit
        @user = params[:id] ? User.find(params[:id]) : current_user
        redirect_to me_path, :notice => "You can't do that." unless current_user == @user || current_organizer
    end

    def update
        @user = params[:id] ? User.find(params[:id]) : current_user
        unless current_user == @user || current_organizer

            redirect_to me_path, :notice => "You can't do that."       
            if @user.update(user_params)
                redirect_to me_path, :notice => 'Updated profile.'
            else
                render :edit
            end
        end
    end

    # POST /users
    # POST /users.json
    def create
        @user = User.new(user_params)

        if @user.save
          session[:user_id] = @user.id
          if(@user.id == 1)
            Organizer.create(:name => @user.name, :user_id => @user.id)
            flash[:warning] = "Since you're the first user in the system, you get to be an organizer."
          end
          redirect_to me_path, :notice => "Successfully created account." 
        else
            render action: 'new' 
        end
    end

    def condense
        @user = User.find(params[:id])
        redirect_to me_path, :notice => "You can't do that." unless current_user == @user || current_organizer
        @registrant = @user.registrants.find(params[:registrant_id])
        @user.condense_charges @registrant
        redirect_to @user, :notice => 'Condensed charges.'
    end

    def bill
        @user = User.find(params[:id])
        redirect_to me_path, :notice => "You can't do that." unless current_user == @user || current_organizer
        @charges = @user.charges
    end

    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <label>Email Address</label>
        <% if current_user == @user %>
            <%= f.text_field :email, :class => 'form-control', :disabled => true %>
        <% else %>
            <%= f.text_field :email, :class => 'form-control' %>
        <% end %>
    </div>

    <div class="form-group">
        <label>Password</label>
        <%= f.password_field :password, :class => 'form-control' %>
    </div>

    <div class="form-group">
        <label>Confirm Password</label>
        <%= f.password_field :password_confirmation, :class => 'form-control' %>
    </div>

    <div class="actions">
        <%= f.submit :class => 'btn btn-success' %>
    </div>
<% end %>

app/views/users/bill.html.erb
<h1>Charges for <%= @user.registrants.map{|r| r.name}.join(', ') %> (<%= @user.email %>)</h1>

<table class="table table-striped">
    <thead>
        <tr class="<%= @user.balance == 0 ? "success" : (@user.balance > 0 ? 'danger' : 'active') %>">
            <td colspan="5">Balance</td>
            <td colspan="1"><%= number_to_currency @user.balance %></td>
        </tr>

        <tr>
            <th>Time</th>
            <th>Registrant</th>
            <th>Charger</th>
            <th><i class="fa fa-usd"></i></th>
            <th>Comment</th>
            <th>Amount</th>
        </tr>
    </thead>

    <tbody>
        <% @charges.each do |charge| %>
            <tr>
                <td><%= charge.created_at.strftime("%Y-%m-%d<br/>%I:%M %P").html_safe %></td>
                <td><%= charge.registrant.name %></td>
                <td><%= charge.charger ? ("<i class=\"fa fa-#{charge.charger.icon}\"></i> " + charge.charger.name).html_safe : "<i class=\"fa fa-desktop\"></i> System".html_safe %></td>
                <td><i class="fa fa-<%= charge.icon || 'usd' %>"></i></td>
                <td><%= charge.comment %><% if charge.description %><p style="font-style: italic;"><%= charge.description %></p><% end %></td>
                <td><%= number_to_currency charge.amount %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<% if current_organizer %>
    <div class="hidden-print">
    <h3>Charge</h3>
    <%= form_tag user_charge_path() do %>
        <%= select_tag :id, options_for_select(@user.registrants.map{|r| [r.name, r.id]}) %>
        <%= text_field_tag :amount, nil, :placeholder => 'Amount', :class => 'form-input' %>
        <%= text_field_tag :comment, nil, :placeholder => 'Comment', :class => 'form-input' %>
        <%= text_field_tag :icon, nil, :placeholder => 'Icon', :class => 'form-input' %>
        <%= text_area_tag :description, nil, :placeholder => 'Description', :class => 'form-input' %>

        <%= submit_tag "Charge", :class => 'btn btn-large btn-success' %>
    <% end %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Cancel', me_path, :class => 'btn btn-warning' %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul class="nav nav-pills">
<% @users.each do |u| %>
  <li><%= link_to u.email, u %></li>
<% end %>
</ul>

<%= link_to 'New User', new_user_path, :class => 'btn btn-success' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if (p = Page.where(:name => 'special#signup')).count > 0 %>
  <%= markdown p.first.body %>
<% end %>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<% if current_user.organizer || current_user.presenter || @user.organizer || @user.presenter %>
<div class="row">
  <div class="col-md-6">
    <% if @user.organizer %>
      <div class="panel power-user">
        <%= image_tag @user.organizer.photo.url(:thumb), :class => 'pull-left' %>
        <h3><%= link_to @user.organizer.name, organizer_path(@user.organizer) %></h3>
        <h4>Organizer</h4>
      </div>
    <% else %>
      <div class="panel boring-user">
        <h3>Not an Organizer</h3>
        <p><%= current_user == @user ? "You are" : "This user is" %> not an organizer.</p>
      </div>
    <% end %>
  </div>
  <div class="col-md-6">
    <% if @user.presenter %>
      <div class="panel power-user">
        <%= image_tag @user.presenter.photo.url(:thumb), :class => 'pull-left' %>
        <h3><%= link_to @user.presenter.name, presenter_path(@user.presenter) %></h3>
        <h4>Presenter</h4>
      </div>
    <% else %>
      <div class="panel boring-user">
        <h3>Not a Presenter</h3>
        <p><%= current_user == @user ? "You are" : "This user is" %> not a presenter.</p>
      </div>
    <% end %>
  </div>
</div>
<% end %>

<% if current_user == @user || current_organizer %>
  <div class="row">
    <div class="col-md-6">
      <h2>Registrants</h2>
      <% if @user.registrants.count > 0 %>
        <% @user.registrants.each do |r| %>
          <div class="registrant">
            <h3><%= r.name %></h3>
            <% if current_organizer %>
              <div>Member of <%= r.memberships.map{|m| m.group.name + ( m.approved ? '' : link_to("!", approve_membership_path(:id => m), :class => 'btn btn-success btn-mini') + ' ') + link_to("X", destroy_membership_path(:id => m), :class => 'btn btn-danger btn-mini')}.join(', ').html_safe %></div>
            <% end %>
            <div><%= link_to 'Redo Survey', qualifiers_path(r) %></div>
            <% if r.events.length > 0 || r.balance != 0 %>
              <table class="table">
                <thead>
                  <tr>
                    <th><%= option('local-event') || 'Event' %></th>
                    <th>Cost</th>
                    <th>Cancel</th>
                  </tr>
                </thead>
                <tbody>
                  <% r.registrations.each do |reg| %>
                    <tr>
                      <td>
                        <%= link_to reg.event.name, event_path(reg.event) %>
                        <% if reg.waiting %><strong>(waitlist!)<% end %>
                        </td>
                        <td><%= number_to_currency reg.event.cost %></td>
                        <td>
                            <% if locked? %>
                                <i class="fa fa-lock"></i>
                            <% else %>
                                <%= link_to 'Cancel', unregister_path(reg.event, :registrant_id => r.id, :event_id => reg.event.id), :class => 'btn btn-mini btn-danger' %> 
                            <% end %>
                        </td>
                        </tr>
                      <% end %>
                      <tr>
                        <td><%= link_to registrant_charges_path(r) do %><b>Total</b> (details) <% end %></td>
                        <td><%= number_to_currency r.balance %></td>
                        <td></td>
                      </tr>
                    </tbody>
                  </table>

                <% else %>
                    <p><%= r.name %> isn't registered for any <%= option('local-events') || 'events' %>.  Maybe you should <%= link_to 'sign up for some', events_path %> or <%= link_to 'remove this registrant', destroy_registrant_path(r) %>.</p>  
                <% end %>
              </div>
            <% end %>
          <% else %>
            <p>You currently don't have any registrants.  You should probably use the form below to add someone.</p>
          <% end %>

          <h3>New Registrant</h3>
          <p>If you would like to register more people, you can add someone here:</p>
          <%= form_tag create_registrant_path do %>
            <%= text_field_tag :name, nil, :class => 'form-input', :placeholder => 'Name' %>
            <%= submit_tag "Go", :class => 'btn btn-success' %>
          <% end %>

        </div>
        <div class="col-md-6">
          <h2>Charges</h2>
          <% if @user.registrants.count > 0 %>
          <table class="table">
            <thead>
              <tr>
                <td><i class="fa fa-cash"></i></td>
                <td colspan="2"><b>Total</b></td>
                <td><%= number_to_currency @user.balance %></td>
              </tr>

              <tr>
                <th><i class="fa fa-usd"></i></th>
                <th>Registrant</th>
                <th>Comment</th>
                <th>Amount</th>
              </tr>
            </thead>

            <tbody>
              <% @user.charges.first(10).each do |charge| %>
                <tr>
                  <td><i class="fa fa-<%= charge.icon || 'usd' %>"></i></td>
                  <td><%=  charge.registrant.name  %></td>
                  <td><%= charge.comment %></td>
                  <td><%= number_to_currency charge.amount %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <% if current_organizer || current_user == @user %>
            <p><%= link_to "View/Print Bill", bill_user_path(@user), :class => 'btn btn-success' %></p>
          <% end %>

          <% if current_organizer %>
            <h3>Charge</h3>
            <%= form_tag user_charge_path do %>
              <%= select_tag :id, options_for_select(@user.registrants.map{|r| [r.name, r.id]}) %>
              <%= text_field_tag :amount, nil, :placeholder => 'Amount', :class => 'form-input' %>
              <%= text_field_tag :comment, nil, :placeholder => 'Comment', :class => 'form-input' %>
              <%= text_field_tag :icon, nil, :placeholder => 'Icon', :class => 'form-input' %>
              <%= text_area_tag :description, nil, :placeholder => 'Description', :class => 'form-input' %>

              <%= submit_tag "Charge", :class => 'btn btn-large btn-success' %>
            <% end %>
          <% end %>

          <% if @user.registrants.count > 1 && (current_user == @user || current_organizer) %>
            <p>
            <%= form_tag condense_user_path(@user), :style => 'display: inline' do %>
              Condense/balance charges onto: <%= select_tag :registrant_id, options_for_select(@user.registrants.map{|r| [r.name, r.id]}) %>
              <%= submit_tag "Condense", :class => 'btn btn-mini btn-warning' %>
            <% end %>
            </p>
          <% end %>
        <% else %>
          <p>There aren't any registrants to charge!</p>
        <% end %>
          <% if current_user == @user %>
            <p><%= link_to 'Change Password', edit_me_path, :class => 'btn btn-primary' %></p>
          <% elsif current_organizer %>
            <p><%= link_to 'Edit', edit_user_path(@user), :class => 'btn btn-primary' %></p>
          <% end %>
        </div>
      </div>
    <% end %>