config/routes.rb
Convocator::Application.routes.draw do
  post "memberships/create", :as => 'create_membership'
  get "memberships/approve", :as => 'approve_membership'
  get "memberships/destroy", :as => 'destroy_membership'

  get "registration" => 'registration#index', :as => 'registration' 
  get "registration/:id" => 'registration#show', :as => 'registrant'
  get "registration/:id/charges" => 'registration#charges', :as => 'registrant_charges'
  post "registration/:id/charge" => 'registration#charge', :as => 'registrant_charge'
  post "registration/charge" => 'registration#charge', :as => 'user_charge'
  post "registration/create", :as => 'create_registrant'
  get "registration/:id/qualify" => 'registration#qualifiers', :as => 'qualifiers'
  post "registration/:id/qualify" => 'registration#qualify', :as => 'qualify'
  post "registration/:id/register" => 'registration#register', :as => 'register'
  get "registration/:id/unregister" => 'registration#unregister', :as => 'unregister'
  get "registration/:id/destroy" => 'registration#destroy', :as => 'destroy_registrant'
  get "registration/:id/unwait" => 'registration#unwait', :as => 'unwait_registration'

  ActiveAdmin.routes(self)
  get "events" => 'events#index', :as => 'events'
  get "events/:id" => 'events#show', :as => 'event'
  post "events/:id" => 'events#update', :as => 'update_event'
  post "events/:id/charge" => 'events#charge', :as => 'charge_event'
  get "events/tagged/:id" => 'events#tagged', :as => 'tag'

  get "about" => 'about#index', :as => 'about'
  get "about/presenters", :as => 'presenters'
  get "about/presenters/:id" => 'about#presenter', :as => 'presenter'
  get "about/organizers", :as => 'organizers'
  get "about/organizers/:id" => 'about#organizer', :as => 'organizer'

  resources :users do
      post 'condense', :on => :member
      get 'bill', :on => :member
  end
  get "me" => 'users#me', :as => 'me'
  get 'me/edit' => 'users#edit', :as => 'edit_me'

  get "sign-in" => 'session#new', :as => 'sign_in'
  get "sign-up" => 'users#new', :as => 'sign_up'
  post "sign-in" => 'session#create', :as => 'session_create'
  get "sign-out" => 'session#destroy', :as => 'sign_out'

  get "pages" => 'pages#index', :as => 'pages'

  get '/:id' => 'pages#show', :as => 'page'

  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
    extend FriendlyId
    include Metahash
    has_many :taggings
    has_many :tags, :through => :taggings
    has_many :assignments
    has_many :presenters, :through => :assignments
    has_many :provisions
    has_many :resources, :through => :provisions
    has_many :registrations
    has_many :registrants, :through => :registrations
    has_many :charges, :as => :charger
    has_many :rulers
    has_many :rules, :through => :rulers
    belongs_to :lock

    friendly_id :name, use: :slugged
    has_attached_file :photo, :styles => {:medium => "300x300>", :thumb => '100x100>'}
    accepts_nested_attributes_for :rules, :allow_destroy => true

    def allows? registrant 
        go = true
        puts "*"*40
        puts "Checking #{registrant.name} for #{self.name}".center(40)

        registrant.events.each do |e|
            if e.end >= self.start && e.start <= self.end
                go = false
                puts "Blocked by Conflict"
            end
        end

        if registrant.user.presenter && (registrant.user.presenter.name == registrant.name)
            registrant.user.presenter.events.each do |e|
                if e.end >= self.start && e.start <= self.end && e != self
                    go = false
                    puts "Blocked by presentation"
                end
            end
        end

        self.rules.where(:group_id => registrant.group_ids << nil).each do |rule|
          allow = rule.allows? registrant
          if allow == true
            go &&= true
            puts "Allowed by R#{rule.id}."
          elsif allow == nil
            puts "R#{rule.id} does not apply."
          else
            go = false
            puts "Blocked by R#{rule.id}."
          end
        end
        puts go ? "OK" : "BLOCKED"
        puts '*'*40
        go
    end

    def unregister_rules registrant 
      self.rules.where(:group_id => registrant.group_ids << nil).each do |rule|
        rule.apply registrant, self
      end
    end


    def register_rules registrant 
      self.rules.where(:group_id => registrant.group_ids << nil).each do |rule|
        rule.apply registrant, self
      end
    end

    def allows registrant
        allows? registrant
    end

    def registrants_for user
        registrants.where(:user_id => user.id)
    end

    def locked?
        lock ? lock.locked : false
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :check_for_presenter, :only => [:update]
  def index
      @events = Event.order(:start)
  end

  def update
    @event = Event.friendly.find(params[:id])
    @event.description = params[:description]
    @event.save
    redirect_to @event, :notice => "Updated description."
  end

  def show
      @event = Event.friendly.find(params[:id])
      if (current_presenter && @event.presenters.include?(current_presenter)) || current_organizer
          @users = @event.registrants.map{|r| r.user}.uniq
      end
  end

  def tagged
  end

  def charge
      @event = Event.friendly.find(params[:id])
      if (current_presenter && @event.presenters.include?(current_presenter)) || current_organizer
          if params[:amount].empty? || params[:comment].empty? || params[:description].empty? || params[:icon].empty?
              redirect_to @event, alert: "Fill out all the fields before charging."
          else
              @event.registrations.where(:waiting => nil).each do |r|
                reg = r.registrant
                charge = reg.charges.build
                charge.charger_type = (current_organizer ? "Organizer" : "Presenter")
                charge.charger_id = (current_organizer ? current_organizer.id : current_presenter.id)
                charge.amount = params[:amount]
                charge.comment = @event.name + " - " + params[:comment]
                charge.description = params[:description]
                charge.icon = params[:icon]
                charge.save
              end
              redirect_to @event, notice: "Charged enrolled registrants."
          end
      end  
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<h1>All <%= option('local-events') || 'Events' %></h1>

<% @events.in_groups_of(2) do |g| %>
  <div class="row">
    <% g.each do |e| %>
      <div class="col-md-6">
        <% if e %>
          <div class="event">
              <% if e.photo.present? %><%= image_tag e.photo.url(:medium) %><% end %>
              <% if e.locked? %>
                  <h3 class="locked-event"><%= fa_icon "lock" %> <% if e.icon %><i class="fa fa-<%= e.icon %>"></i> <% end %><%= link_to e.name, event_path(e) %> <%= fa_icon "lock" %></h3>
              <% else %>
                  <h3><% if e.icon %><i class="fa fa-<%= e.icon %>"></i> <% end %><%= link_to e.name, event_path(e) %></h3>
              <% end %>
            <h4>
              <% if e.end - e.start < 60*60*24 %>
                <%= e.start.strftime '%Y-%m-%d %I:%M %P' %> - <%= e.end.strftime '%I:%M %P' %>
              <% else %>
                <%= e.start.strftime '%Y-%m-%d %I:%M %P' %> - <%= e.end.strftime '%Y-%m-%d %I:%M %P' %>
              <% end %>
            </h4>
            <% presenters = current_organizer ? e.presenters : e.presenters.where(:public => true) %>
            <% if presenters.count > 0 %>
              <h5>Presented by <%= presenters.map{|p| link_to(p.name, presenter_path(p), :class => (p.public ? '' : 'secret-presenter'))}.join(', ').html_safe %></h5>
            <% end %>
            <% if e.limit %>
              <p><i><% if !e.locked? %> <%= e.registrations.where(:waiting => nil).count %> registered -<% end %> <%= el = e.limit - e.registrations.where(:waiting => nil).count; el > 0 ? el : '0'  %> seats left.</i><% if (current_presenter || current_organizer) && e.registrations.where(:waiting => true).count > 0 %> <%= e.registrations.where(:waiting => true).count %> on waitlist.<% end %></p>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <% end %>

app/views/events/show.html.erb
<div class="event">
  <% if @event.photo.present? %><%= image_tag @event.photo.url(:medium) %><% end %>
              <% if @event.locked? %>
                  <h2 class="locked-event"><%= fa_icon "lock" %> <% if @event.icon %><i class="fa fa-<%= @event.icon %>"></i> <% end %><%= @event.name %> <%= fa_icon "lock" %></h2>
              <% else %>
                  <h2><% if @event.icon %><i class="fa fa-<%= @event.icon %>"></i> <% end %><%= @event.name %></h2>
              <% end %>
  <h4>
    <% if @event.end - @event.start < 60*60*24 %>
      <%= @event.start.strftime '%Y-%m-%d %I:%M %P' %> - <%= @event.end.strftime '%I:%M %P' %>
    <% else %>
      <%= @event.start.strftime '%Y-%m-%d %I:%M %P' %> - <%= @event.end.strftime '%Y-%m-%d %I:%M %P' %>
    <% end %>
  </h4>
  <% presenters = current_organizer ? @event.presenters : @event.presenters.where(:public => true) %>
  <% if presenters.count > 0 %>
    <h5>Presented by <%= presenters.map{|p| link_to(p.name, presenter_path(p), :class => (p.public ? '' : 'secret-presenter'))}.join(', ').html_safe %></h5>
  <% end %>
  <p>
  <% if @event.limit %><i><% if !@event.locked? %><%= @event.registrations.where(:waiting => nil).count %> registered - <% end %><%= el = @event.limit - @event.registrations.where(:waiting => nil).count; ((current_presenter || current_organizer) && el < 0) ? el : '0'  %> seats left.</i><% end %>
  <% if current_user && (q = current_user.registrants.to_a.keep_if{|r| @event.registrants.include? r}).count > 0 %>
    - <%= q.map{|r| r.waiting_on?(@event) ? r.name + " (waitlist)" : r.name}.join(', ') %> <%= q.count == 1 ? 'is' : 'are' %> registered.
  <% end %>
  </p>
  <%= markdown @event.description, @event %>

  <% if option('blurb-event') %>
    <%= markdown option('blurb-event'), @event %>
  <% end %>
</div>


<% if (current_presenter && @event.presenters.include?(current_presenter)) || current_organizer %>
    <div class="row">
        <div class="col-md-6">
  <h2>Update Description</h2>
  <%= form_tag update_event_path(@event) do %>
    <%= text_area_tag :description, @event.description %>
    <%= submit_tag "Update", :class => 'btn btn-warning btn-large' %>
<% end %>
</div>
<div class="col-md-6">
<h2>Charge Active Registrants</h2>
            <%= form_tag charge_event_path do %>
              <%= text_field_tag :amount, nil, :placeholder => 'Amount', :class => 'form-input' %>
              <%= text_field_tag :comment, nil, :placeholder => 'Comment', :class => 'form-input' %>
              <%= text_field_tag :icon, nil, :placeholder => 'Icon', :class => 'form-input' %>
              <%= text_area_tag :description, nil, :placeholder => 'Description', :class => 'form-input' %>

              <%= submit_tag "Charge", :class => 'btn btn-large btn-success' %>
          <% end %>
      </div>
  </div>

  <h2>Registrations</h2>
  <table class="table table-striped">
    <thead>
      <th>User</th>
      <th>Registrants</th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.email, "mailto:#{user.email}" %></td>
          <td>
            <%= @event.registrants_for(user).map do |r|
              r.waiting_on?(@event) ? link_to(r.name_with_groups, r.user, :class => 'waitlisted') + " " + link_to('Promote', unwait_registration_path(r.registrations.where(:event => @event).first), :class => 'btn btn-mini btn-success') : link_to(r.name_with_groups, r.user)
            end.join(', ').html_safe %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if current_user && !@event.locked? %>
  <h2>Register for <%= @event.name %></h2>
  <% if current_user.registrants.count > 0 %>
    <% registrants = current_user.registrants.to_a.delete_if{|r| !@event.allows? r}.delete_if{|r| @event.registrants.include? r} %>
    <% if registrants.count > 0 %>
      <%= form_tag register_path do %>
        <%= select_tag :registrant_id, options_for_select(registrants.map{|r| [r.name, r.id]}) %>
        <%= hidden_field_tag :event_id, @event.id %>
        <%= submit_tag 'Register!', :class => 'btn btn-primary' %>
      <% end %>
    <% else %>
      <p>None of your registrants are allowed to register for this event.</p>
    <% end %>
  <% else %>
    <p>You don't have any registrants associated with your account.  Please create one <%= link_to 'here', registration_path %></p>
  <% end %>
<% end %>

app/views/events/tagged.html.erb
<h1>Events#tagged</h1>
<p>Find me in app/views/events/tagged.html.erb</p>