config/routes.rb
Convocator::Application.routes.draw do
  post "memberships/create", :as => 'create_membership'
  get "memberships/approve", :as => 'approve_membership'
  get "memberships/destroy", :as => 'destroy_membership'

  get "registration" => 'registration#index', :as => 'registration' 
  get "registration/:id" => 'registration#show', :as => 'registrant'
  get "registration/:id/charges" => 'registration#charges', :as => 'registrant_charges'
  post "registration/:id/charge" => 'registration#charge', :as => 'registrant_charge'
  post "registration/charge" => 'registration#charge', :as => 'user_charge'
  post "registration/create", :as => 'create_registrant'
  get "registration/:id/qualify" => 'registration#qualifiers', :as => 'qualifiers'
  post "registration/:id/qualify" => 'registration#qualify', :as => 'qualify'
  post "registration/:id/register" => 'registration#register', :as => 'register'
  get "registration/:id/unregister" => 'registration#unregister', :as => 'unregister'
  get "registration/:id/destroy" => 'registration#destroy', :as => 'destroy_registrant'
  get "registration/:id/unwait" => 'registration#unwait', :as => 'unwait_registration'

  ActiveAdmin.routes(self)
  get "events" => 'events#index', :as => 'events'
  get "events/:id" => 'events#show', :as => 'event'
  post "events/:id" => 'events#update', :as => 'update_event'
  post "events/:id/charge" => 'events#charge', :as => 'charge_event'
  get "events/tagged/:id" => 'events#tagged', :as => 'tag'

  get "about" => 'about#index', :as => 'about'
  get "about/presenters", :as => 'presenters'
  get "about/presenters/:id" => 'about#presenter', :as => 'presenter'
  get "about/organizers", :as => 'organizers'
  get "about/organizers/:id" => 'about#organizer', :as => 'organizer'

  resources :users do
      post 'condense', :on => :member
      get 'bill', :on => :member
  end
  get "me" => 'users#me', :as => 'me'
  get 'me/edit' => 'users#edit', :as => 'edit_me'

  get "sign-in" => 'session#new', :as => 'sign_in'
  get "sign-up" => 'users#new', :as => 'sign_up'
  post "sign-in" => 'session#create', :as => 'session_create'
  get "sign-out" => 'session#destroy', :as => 'sign_out'

  get "pages" => 'pages#index', :as => 'pages'

  get '/:id' => 'pages#show', :as => 'page'

  root 'welcome#index'

end

app/models/charge.rb
class Charge < ActiveRecord::Base
    belongs_to :registrant
    belongs_to :charger, :polymorphic => true
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]

  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.all
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @charge }
      else
        format.html { render action: 'new' }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_params
      params.require(:charge).permit(:amount, :comment, :description, :icon)
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.erb
<%= form_for(@charge) do |f| %>
  <% if @charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% @charge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.text_field :icon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charges/edit.html.erb
<h1>Editing charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<h1>Listing charges</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Comment</th>
      <th>Description</th>
      <th>Icon</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @charges.each do |charge| %>
      <tr>
        <td><%= charge.amount %></td>
        <td><%= charge.comment %></td>
        <td><%= charge.description %></td>
        <td><%= charge.icon %></td>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/new.html.erb
<h1>New charge</h1>

<%= render 'form' %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @charge.amount %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @charge.comment %>
</p>

<p>
  <strong>Description:</strong>
  <%= @charge.description %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @charge.icon %>
</p>

<%= link_to 'Edit', edit_charge_path(@charge) %> |
<%= link_to 'Back', charges_path %>