config/routes.rb
Convocator::Application.routes.draw do
  post "memberships/create", :as => 'create_membership'
  get "memberships/approve", :as => 'approve_membership'
  get "memberships/destroy", :as => 'destroy_membership'

  get "registration" => 'registration#index', :as => 'registration' 
  get "registration/:id" => 'registration#show', :as => 'registrant'
  get "registration/:id/charges" => 'registration#charges', :as => 'registrant_charges'
  post "registration/:id/charge" => 'registration#charge', :as => 'registrant_charge'
  post "registration/charge" => 'registration#charge', :as => 'user_charge'
  post "registration/create", :as => 'create_registrant'
  get "registration/:id/qualify" => 'registration#qualifiers', :as => 'qualifiers'
  post "registration/:id/qualify" => 'registration#qualify', :as => 'qualify'
  post "registration/:id/register" => 'registration#register', :as => 'register'
  get "registration/:id/unregister" => 'registration#unregister', :as => 'unregister'
  get "registration/:id/destroy" => 'registration#destroy', :as => 'destroy_registrant'
  get "registration/:id/unwait" => 'registration#unwait', :as => 'unwait_registration'

  ActiveAdmin.routes(self)
  get "events" => 'events#index', :as => 'events'
  get "events/:id" => 'events#show', :as => 'event'
  post "events/:id" => 'events#update', :as => 'update_event'
  post "events/:id/charge" => 'events#charge', :as => 'charge_event'
  get "events/tagged/:id" => 'events#tagged', :as => 'tag'

  get "about" => 'about#index', :as => 'about'
  get "about/presenters", :as => 'presenters'
  get "about/presenters/:id" => 'about#presenter', :as => 'presenter'
  get "about/organizers", :as => 'organizers'
  get "about/organizers/:id" => 'about#organizer', :as => 'organizer'

  resources :users do
      post 'condense', :on => :member
      get 'bill', :on => :member
  end
  get "me" => 'users#me', :as => 'me'
  get 'me/edit' => 'users#edit', :as => 'edit_me'

  get "sign-in" => 'session#new', :as => 'sign_in'
  get "sign-up" => 'users#new', :as => 'sign_up'
  post "sign-in" => 'session#create', :as => 'session_create'
  get "sign-out" => 'session#destroy', :as => 'sign_out'

  get "pages" => 'pages#index', :as => 'pages'

  get '/:id' => 'pages#show', :as => 'page'

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= option('site-title') || 'Convocator' %></title>
        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>

        <!-- Fixed navbar -->
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <%= link_to option('site-title') || 'Convocator', root_path, :class => 'navbar-brand' %> 
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <%= link_to 'Information <b class="caret"></b>'.html_safe, '#', :class => 'dropdown-toggle', :"data-toggle" => 'dropdown' %>
                            <ul class="dropdown-menu">
                                <li><%= link_to "About Us", about_path %></li>
                                <% if Organizer.where(:public => true).count > 0 %><li><%= link_to "Organizers", organizers_path %></li><% end %>
                                <% if Presenter.where(:public => true).count > 0 %><li><%= link_to "Presenters", presenters_path %></li><% end %>
                            </ul>
                        </li>
                        <li><%= link_to (option('local-events') || 'Events'), events_path %></li>
                        <% Navigator.where(:parent_id => nil).each do |n| %>
                            <% if n.children.length > 0 %>
                                <li class='dropdown'>
                                <%= link_to (n.name + ' <b class="caret"></b>').html_safe, '#', :class => 'dropdown-toggle', :"data-toggle" => 'dropdown' %>
                                <ul class="dropdown-menu">
                                    <% n.children.each do |m| %>
                                        <li><%= link_to( ((m.page.meta['icon'] ? "<i class='fa fa-#{m.page.meta["icon"]}'></i> " : '') + m.name).html_safe, page_path(m.page)) %></li>
                                    <% end %>
                                </ul>
                                </li>
                            <% else %>
                                <li><%= link_to(((n.page.meta['icon'] ? "<i class='fa fa-#{n.page.meta["icon"]}'></i> " : '') + n.name).html_safe, page_path(n.page)) %></li>
                            <% end %>
                        <% end %>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <% if current_user %>
                            <% if current_organizer || current_presenter %>
                                <li class="dropdown">
                            <%= link_to 'Tools <b class="caret"></b>'.html_safe, '#', :class => 'dropdown-toggle', :"data-toggle" => 'dropdown' %>
                            <ul class="dropdown-menu">
                              <% if current_presenter %>
                                <li><%= link_to "My Presentations", presenter_path(current_presenter) %></li>
                              <% end %>
                                <% if current_organizer %>
                                    <li><%= link_to "Admin Panel", root_url + 'admin/' %></li>
                                    <li><%= link_to "Users", users_path %></li>
                                <% end %>
                            </ul>
                                </li>
                            <% else %>
                            <% end %>
                            <li><%= link_to current_user.email, me_path %></li>
                            <li><%= link_to 'Sign Out', sign_out_path %></li>
                        <% else %>
                            <li><%= link_to 'Sign In', sign_in_path %></li>
                            <li><%= link_to 'Sign Up', sign_up_path %></li>
                        <% end %>
                         <li class="dropdown">
                        <%= link_to '#', :class => 'dropdown-toggle', :'data-toggle' => 'dropdown' do %>
                            <span id="flash-link" <%= flash.count > 0 ? 'class="active"'.html_safe : '' %>><i class="fa fa-bell"></i> <span id="flash-counter"><%= flash.count %></span></span>
                        <% end %>
                        <ul class="dropdown-menu">
                            <% if flash.count > 0 %>
                                <%= bootstrap_flash %>
                            <% else %>
                                <li id="flashPlaceholder"><a href="#">No alerts for you!</a></li>
                            <% end %>
                        </ul>
                        </li>
                   </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <div class="container">
            <%= yield %>
        </div>

    </body>
</html>